spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL:jdbc:postgresql://postgres:5432/guidepedia_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123}
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.liquibase.change-log=classpath:db/changelog/liquidbase-changeLog.xml
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
jwt.secret=${JWT_SECRET:guidepediaSecretKey}
jwt.sessionTime=${JWT_SESSION_TIME:36000000}
jwt.refreshSessionTime=${JWT_REFRESH_SESSION_TIME:86400000}
